import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageTitle from "../../components/PageTitle";
import RelatedBlogs from "../../components/RelatedBlogs";
import { FeaturedBlog, Product } from "../interfaces";
interface Props {
  blogData: FeaturedBlog;
  featuredBlogsData: FeaturedBlog[];
}

const BlogDetail: NextPage<Props> = ({ blogData, featuredBlogsData }) => {
  const { author, category, title, date, img, first_content, second_content } =
    blogData;

  return (
    <>
      <Head>
        <title>Store - title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={title} />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={img} alt="IMG-BLOG" />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">
                      {category}
                    </span>

                    <span>
                      <span className="cl4">By</span> {author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>{date}</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{title}</h4>

                  <p className="stext-117 cl6 p-b-26">{first_content}</p>

                  <p className="stext-117 cl6 p-b-26">{second_content}</p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <RelatedBlogs featuredBlogsData={featuredBlogsData} />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const resBlogs = await fetch("http://localhost:5001/blogs");
  const blogs: Product[] = await resBlogs.json();

  const paths = blogs.map((el) => ({
    params: {
      id: el.id,
    },
  }));

  return {
    paths,
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params && params.id) {
    const randomNum = Math.floor(Math.random() * 20 + 1);

    const res = await fetch(`http://localhost:5001/blogs/${params.id}`);
    const blogData: FeaturedBlog[] = await res.json();

    const featuredBlogsRes = await fetch(
      `http://localhost:5001/products?_start=${randomNum}&_limit=4`
    );
    const featuredBlogsData = await featuredBlogsRes.json();

    if (Object.keys(blogData).length === 0) {
      return {
        notFound: true,
      };
    }

    return {
      props: {
        blogData,
        featuredBlogsData,
      },
    };
  }

  return {
    notFound: true,
  };
};

export default BlogDetail;
