import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { FeaturedBlog, Product } from "./interfaces";

interface Props {
  bannerContentData: {
    preTitle: string;
    title: string;
  };
  featuredProductsData: Product[];
  featuredBlogsData: FeaturedBlog[];
}

const Home: NextPage<Props> = ({
  bannerContentData,
  featuredProductsData,
  featuredBlogsData,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner bannerContentData={bannerContentData} />

      <CategoryPicker />

      <FeaturedProducts featuredProductsData={featuredProductsData} />

      <FeaturedBlogs featuredBlogsData={featuredBlogsData} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/banner_content");
  const bannerContentData = await res.json();

  const resMaleGender = await fetch("http://localhost:5001/products");

  const featuredProductsRes = await fetch(
    "http://localhost:5001/products/?_limit=4"
  );
  const featuredProductsData = await featuredProductsRes.json();

  const featuredBlogsRes = await fetch("http://localhost:5001/blogs/?_limit=3");
  const featuredBlogsData = await featuredBlogsRes.json();

  return {
    props: {
      bannerContentData,
      featuredProductsData,
      featuredBlogsData,
    },
  };
};

export default Home;
