import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import BlogItem from "../components/BlogItem";
import PageTitle from "../components/PageTitle";
import ProductItem from "../components/ProductItem";
import { FeaturedBlog, Product } from "./interfaces";

interface Props {
  products: Product[];
  featuredBlogsData: FeaturedBlog[];
}

const Search: NextPage<Props> = ({ products, featuredBlogsData }) => {
  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Search" />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          {/* blogs  */}

          <>
            <h2 className="mb-5">Blogs</h2>
            <div className="row isotope-grid">
              {/* blog skeleton - search result */}
              {featuredBlogsData.length > 0 ? (
                featuredBlogsData.map((blog) => (
                  <div key={blog.id} className="col-4">
                    {" "}
                    <BlogItem blog={blog} />{" "}
                  </div>
                ))
              ) : (
                <h5 className="mb-5 pl-3">
                  There are no blogs based on your filter.
                </h5>
              )}
              {/* !! */}
            </div>
          </>

          {/* products */}
          <>
            <h2 className="mb-5">Products</h2>
            <div className="row isotope-grid">
              {/* product skeleton */}
              {products.length > 0 ? (
                products.map((product) => (
                  <ProductItem product={product} key={product.id} />
                ))
              ) : (
                <h5 className="mb-5 pl-3">
                  There are no products based on your filter.
                </h5>
              )}
              {/* !! */}
            </div>
          </>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const { q } = query;

  const blogsRes = await fetch(
    `http://localhost:5001/blogs?${q ? `q=${q}` : ""}`
  );
  const featuredBlogsData = await blogsRes.json();

  const resProd = await fetch(
    `http://localhost:5001/products?&${q ? `q=${q}` : ""}`
  );
  const products = await resProd.json();

  return {
    props: {
      products,
      // featuredProductsData,
      featuredBlogsData,
    },
  };
};

export default Search;
